//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_user
    {
        public int userID { get; set; }
        public string userName { get; set; }
        public string email { get; set; }
        public Nullable<int> password { get; set; }
        public string remarks { get; set; }
    }
}
