//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Employee = new HashSet<Employee>();
            this.Leave = new HashSet<Leave>();
            this.Salary = new HashSet<Salary>();
        }
    
        public int departmentID { get; set; }
        public string departmentName { get; set; }
        public string departmentLocation { get; set; }
        public string headOfDepartment { get; set; }
    
        public virtual ICollection<Employee> Employee { get; set; }
        public virtual ICollection<Leave> Leave { get; set; }
        public virtual ICollection<Salary> Salary { get; set; }
    }
}
