//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Leave = new HashSet<Leave>();
            this.Salary = new HashSet<Salary>();
        }
    
        public int employeeID { get; set; }
        public string employeeName { get; set; }
        public Nullable<int> departmentID { get; set; }
        public Nullable<int> designationID { get; set; }
        public string email { get; set; }
        public Nullable<long> phone { get; set; }
        public string remarks { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Designation Designation { get; set; }
        public virtual ICollection<Leave> Leave { get; set; }
        public virtual ICollection<Salary> Salary { get; set; }
    }
}
