//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public int salaryID { get; set; }
        public Nullable<int> departmentID { get; set; }
        public Nullable<int> employeeID { get; set; }
        public Nullable<int> salary1 { get; set; }
        public Nullable<int> tax { get; set; }
        public Nullable<int> penalty { get; set; }
        public Nullable<int> netSalary { get; set; }
        public string remarks { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
