//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacancy
    {
        public int vacancyID { get; set; }
        public string position { get; set; }
        public string qualification { get; set; }
        public Nullable<int> experience { get; set; }
        public string remarks { get; set; }
    }
}
